name: al_quran
description: "Quran Pak App"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.6.1







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  dio: ^5.3.3
  retrofit_generator: ^9.1.9
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  iconsax: ^0.0.8
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.10
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  flex_color_scheme: ^8.1.0
  url_launcher: ^6.3.0
  lottie: ^3.3.1
  flutter_gif: ^0.0.4
  intl: ^0.20.2
  flutter_swipe_action_cell: ^3.1.5
  faded_scrollable: ^1.0.1
  flutter_svg: ^2.0.17


  ##nosql database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.4.0
  flutter_qiblah: ^3.1.0+1
  adhan: ^2.0.0+1
  freezed_annotation: ^3.0.0
  light_dark_theme_toggle: ^1.1.2


  ##

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  simple_gradient_text: 1.3.0
  hive_generator: ^2.0.1
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.0




flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/



  fonts:
    - family: IBM-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
    - family: IBM-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
    - family: IBM-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: Not-Bold
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Bold.ttf
    - family: Not-Medium
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Medium.ttf
    - family: Not-Regular
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Lita-Regular
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Ex-Bold
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
    - family: Ex-Medium
      fonts:
        - asset: assets/fonts/Exo2-Medium.ttf
    - family: Ex-Regular
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
    - family: Special-A
      fonts:
        - asset: assets/fonts/special/special-1.ttf
    - family: Special-B
      fonts:
        - asset: assets/fonts/special/special-2.ttf
    - family: Special-C
      fonts:
        - asset: assets/fonts/special/special-3.ttf
    - family: Special-D
      fonts:
        - asset: assets/fonts/special/special-4.ttf
    - family: Special-E
      fonts:
        - asset: assets/fonts/special/special-5.ttf
    - family: Special-F
      fonts:
        - asset: assets/fonts/special/special-6.ttf


  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
